// src/main.rs

    mod db;
    mod models;
    mod schema; // This file is generated by Diesel.
    mod handlers;
    mod utils;
    mod middleware;
    mod server;
    mod config;
    mod routes;

    use db::establish_connection_pool;

    #[tokio::main]
    async fn main() {
        config::load_env();


        // Initialize the database connection pool
        let pool = establish_connection_pool();

        // Create router with routes
        let app = routes::create_routes(pool);

        // Run the server
        server::run_server(app.await).await;
    }